description = "Jupyter Kernel for Ada"
long-description = '''# Jupyter Kernel for Ada

To run this kernel with Jupyter Notebook:
    alr get --build jupyter_kernel
    cd jupyter_kernel*
    JUPYTER_PATH=$PWD jupyter-notebook --debug
'''

name = "jupyter_kernel"
version = "1.0.0"
website = "https://github.com/reznikmm/jupyter/"
authors = ["Max Reznik"]
licenses = ["BSD 3-Clauses"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/jupyter_ada_kernel.gpr", "gnat/jupyter_ada_driver.gpr"]
tags = ["jupyter", "notebook", "kernel"]

[gpr-set-externals]
LIBRARY_TYPE = "relocatable"

# The Ada Kernel uses `dlopen` to load shared libraries
[available.'case(os)']
linux   = true
macos   = true
'...'   = false

[[depends-on]]
matreshka_league = "any"
spawn = "any"
zeromq_ada = "any"
