description = "Jupyter Kernel for Ada"
long-description = '''# Jupyter Kernel for Ada

To run this kernel with Jupyter Notebook:
    alr get --build jupyter_kernel
    cd jupyter_kernel*
    JUPYTER_PATH=$PWD jupyter-notebook --debug
'''

name = "jupyter_kernel"
version = "1.1.0"
website = "https://github.com/reznikmm/jupyter/"
authors = ["Max Reznik"]
licenses = "BSD-3-Clause"
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/jupyter_ada_kernel.gpr"]
tags = ["jupyter", "notebook", "kernel"]

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false

# The Ada Kernel uses `dlopen` to load shared libraries
[available.'case(os)']
linux   = true
macos   = true
'...'   = false

[[depends-on]]
matreshka_league = "any"
spawn = "any"
zeromq_ada = "any"

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"
