# SPDX-FileCopyrightText: 2020 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: jupyter
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
        with:
          args: --root jupyter lint
      - uses: reznikmm/fedora-ada-action@v3
        with:
          spec: jupyter/packages/jupyter-ada.spec
      - name: Upload tar-ball to Bintray
        uses: reznikmm/upload-bintray-action@v3
        with:
          subject: reznikmm
          repository: matreshka
          package: jupyter-ada
          version: head-fc33
          sourcePath: x86_64/*
          override: 1
          username: reznikmm
          apiKey: ${{secrets.BINTRAY_API_KEY}}
