# SPDX-FileCopyrightText: 2020-2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

on:
  pull_request:
  push:
    branches:
      - master
      - topic/*
name: Build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xxx:
          - os: ubuntu-20.04
            env: OS=unix
          - os: macos-12
            env: OS=osx
          - os: macos-14
            env: OS=osx

    runs-on: ${{ matrix.xxx.os }}
    name: On
    steps:
      - uses: actions/checkout@v2
        with:
          path: jupyter
      - name: Get alire
        if: runner.arch != 'ARM64'
        uses: alire-project/setup-alire@v3
        with:
          toolchain: gnat_native gprbuild

      - name: Get alire (ARM64)
        if: runner.arch == 'ARM64'
        run: |
          curl -L -O https://github.com/simonjwright/alire-index.mac/releases/download/alr-2.0.1-bin-aarch64-macos/alr-2.0.1-bin-aarch64-macos.zip
          unzip alr-2.0.1-bin-aarch64-macos.zip
          export PATH=$PWD/bin:$PATH
          alr index --reset-community
          alr index \
             --add=git+https://github.com/simonjwright/alire-index.mac.git \
             --before=community \
             --name=index_for_mac
          alr toolchain --select gprbuild gnat_native
          echo $PWD/bin >> $GITHUB_PATH

      - name: Alire build
        run: |
          eval ${{ matrix.xxx.env }}
          echo $PATH
          alr index --before=community --add git+https://github.com/reznikmm/alire-index.git#topic/zeromq --name myindex
          LIBRARY_TYPE=relocatable alr -C jupyter build
