# SPDX-FileCopyrightText: 2022-2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

on:
  push:
    branches:
      - test
    tags:
      - v[0-9]*
name: Build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xxx:
          - os: ubuntu-20.04
            env: OS=unix
          - os: macos-12
            env: OS=osx
          - os: macos-14
            env: OS=osx

    runs-on: ${{ matrix.xxx.os }}

    name: Build and deploy static binaries
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: zeromq/libzmq
          path: libzmq
      - name: Get alire
        if: runner.arch != 'ARM64'
        uses: alire-project/setup-alire@v3
        with:
          toolchain: gnat_native gprbuild

      - name: Install autotools (MacOS)
        if: runner.os == 'macOS'
        run: brew install libtool autoconf automake

      - name: Get alire (ARM64)
        if: runner.arch == 'ARM64'
        run: |
          curl -L -O https://github.com/simonjwright/alire-index.mac/releases/download/alr-2.0.1-bin-aarch64-macos/alr-2.0.1-bin-aarch64-macos.zip
          unzip alr-2.0.1-bin-aarch64-macos.zip
          rm -f alr-2.0.1-bin-aarch64-macos.zip
          export PATH=$PWD/bin:$PATH
          alr index --reset-community
          alr index \
             --add=git+https://github.com/simonjwright/alire-index.mac.git \
             --before=community \
             --name=index_for_mac
          alr toolchain --select gprbuild gnat_native
          echo $PWD/bin >> $GITHUB_PATH

      - name: Alire build
        run: |
          eval ${{ matrix.xxx.env }}
          alr settings --set dependencies.shared False
          alr settings --set distribution.disable_detection True
          alr exec .github/workflows/build.sh

      - name: Save binary as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ada_kernel-${{ runner.os }}
          path: '*.zip'
      - name: Upload release
        run: |
          if [[ ${GITHUB_REF##*/} = v[0-9]* ]]; then
              .github/workflows/release.sh "${{ secrets.GITHUB_TOKEN }}"
          fi
